### ISSUE TITLE
Problem with `sourceType` after upgrading from 0.1.0 to 1.0.0

### ISSUE THREAD

**Issue by zdila** [jonschlinkert/babel-extract-comments#2]
```
(node:17217) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: 'import' and 'export' may appear only with 'sourceType: "module"' (1:0)
(node:17217) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by doowb** [comment]
@zdila can you provide more information?
- Example of code with comments being extract?
- Example of code using this library?

**Comment by zdila** [comment]
The error was:

```
unhandledRejection { SyntaxError: 'import' and 'export' may appear only with 'sourceType: "module"' (1:0)
    at Parser.pp$5.raise (/home/fred/myproject/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp$1.parseStatement (/home/fred/myproject/node_modules/babylon/lib/index.js:1881:16)
    at Parser.pp$1.parseBlockBody (/home/fred/myproject/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseTopLevel (/home/fred/myproject/node_modules/babylon/lib/index.js:1778:8)
    at Parser.parse (/home/fred/myproject/node_modules/babylon/lib/index.js:1673:17)
    at Object.parse (/home/fred/myproject/node_modules/babylon/lib/index.js:7305:37)
    at extract (/home/fred/myproject/node_modules/babel-extract-comments/index.js:33:23)
    at module.fileDependencies.forEach (/home/fred/myproject/build-tool/SwaggerPlugin.js:24:32)
    at Array.forEach (<anonymous>)
    at chunk.forEachModule (/home/fred/myproject/build-tool/SwaggerPlugin.js:22:35)
    at Set.forEach (<anonymous>)
    at Chunk.forEachModule (/home/fred/myproject/node_modules/webpack/lib/Chunk.js:159:17)
    at compilation.chunks.forEach (/home/fred/myproject/build-tool/SwaggerPlugin.js:20:13)
    at Array.forEach (<anonymous>)
    at Compiler.compiler.plugin (/home/fred/myproject/build-tool/SwaggerPlugin.js:19:24)
    at next (/home/fred/myproject/node_modules/tapable/lib/Tapable.js:204:14) pos: 0, loc: Position { line: 1, column: 0 } }
```

I had to add `{ sourceType: 'module' }` option to make it working. Plugin now also keeps ` * `s in the comment if it is in the following format:

```
/**
 * foo
 * bar
 */
```

As it is a major version change, this new behaviour is allowed ;-)
